### ISSUE TITLE
Panic on deleting statefulset on kubernetes 1.8.1-gke.0

### ISSUE THREAD

**Issue by hartfordfive** [kubernetes/kubectl#107]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?**:  BUG REPORT

**Kubernetes version**:   1.8.1-gke.0

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release):  Container-Optimized OS
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:
   - Google Cloud SDK 177.0.0
- **kubectl version output**:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-gke.0", GitCommit:"a8e22959b5a4c0ca54ef8860231074428c962466", GitTreeState:"clean", BuildDate:"2017-10-12T19:32:15Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:

When setting a zookeeper cluster, as described in your official example [here](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/), I ran into a panic when deleting the statefulset.  Consequently, the statefulset doesn't get deleted, therefore the only way to get rid of it is by removing the related namespace.

**What you expected to happen**:

It should have deleted the stateful set and returned successfully

**How to reproduce it** (as minimally and precisely as possible):

```
kubectl delete -f k8s/13-stateful-set.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x226024]

goroutine 1 [running]:
panic(0x17ceb20, 0xc42000e0e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/kubectl.ReaperFor(0xc420319800, 0x4, 0xc420319860, 0xb, 0x0, 0x0, 0x1805c20, 0xc42025a730, 0xc4209f5320, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/stop.go:92 +0x1244
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ring1Factory).Reaper(0xc42025a080, 0xc4202a7730, 0x109e5, 0xc4202ab320, 0xc4209f5338, 0x1d6603)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory_object_mapping.go:290 +0x151
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*factory).Reaper(0xc42072e240, 0xc4202a7730, 0x19a46e0, 0xc42002e788, 0xc4209f5490, 0x17a332)
	<autogenerated>:92 +0x54
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult.func1(0xc4203cee80, 0x0, 0x0, 0x9, 0x24e701)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:252 +0xdb
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc4203cee80, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:348 +0x153
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc4203cee80, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:324 +0xe5
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4203cee80, 0x0, 0x0, 0xc4209f5640, 0x436d5)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:389 +0x57c
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit.func1(0xc4203cee80, 0x0, 0x0, 0x1000, 0xc420045dd0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:207 +0x153
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc4200d5d00, 0xc420855fa0, 0x2625c20, 0xc42085c000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:552 +0x308
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc420855e40, 0xc420855fa0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:501 +0x184
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc4203196e0, 0x1, 0x1, 0xc420713740, 0x1, 0xc420713740)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:211 +0xf4
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc420855ee0, 0xc420713740, 0x0, 0x1adfae6)
	<autogenerated>:122 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2621ce0, 0xc420855ee0, 0xc4200d5cc0, 0xc4200d5d40, 0xc420855f01, 0xc4200d5d40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:417 +0x94
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc420855f00, 0xc4200d5d40, 0x18, 0x18)
	<autogenerated>:138 +0x6e
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2621d60, 0xc420855f00, 0xc4203196f0, 0x2, 0x2, 0xc420855f60, 0xc420319701, 0xc420855f60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:325 +0xd6
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc420713710, 0xc420855f60, 0x184f400, 0xc41ffe40a4)
	<autogenerated>:158 +0x78
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x2621c60, 0xc420713710, 0xc42037eb60, 0x2c44000, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:352 +0xf1
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc420319700, 0xc42037eb60, 0xfec8, 0x70)
	<autogenerated>:153 +0x65
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc42037eaf0, 0xc42037eb60, 0x26e1d10, 0x2621c60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:96 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd.ReapResult(0xc42037eaf0, 0x2644260, 0xc42072e240, 0x2620c60, 0xc42002e010, 0x2620001, 0x0, 0xffffffffffffffff, 0x2630000, 0x263bfa0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:277 +0x16f
k8s.io/kubernetes/pkg/kubectl/cmd.(*DeleteOptions).RunDelete(0xc420210f20, 0x2644260, 0xc42072e240)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:237 +0xc5
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDelete.func1(0xc4203d78c0, 0xc4203039c0, 0x0, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/delete.go:143 +0x17c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203d78c0, 0xc420303860, 0x2, 0x2, 0xc4203d78c0, 0xc420303860)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x439
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202fe000, 0xc4204252f0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x367
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4202fe000, 0xc42072e240, 0x2620c20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
```

**Anything else we need to know**:

**Comment by apelisse** [comment]
> ```
> Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.1-gke.0", GitCommit:"a8e22959b5a4c0ca54ef8860231074428c962466", GitTreeState:"clean", BuildDate:"2017-10-12T19:32:15Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
> ```

Kubectl is not tested nor supported with more than 1 version skew. Can you update your version of Kubectl and see if it still fails?

Thank you,

**Comment by hartfordfive** [comment]
@apelisse I updated my kubectl client to a recent version and that did fixed the issue.  Thanks for your help.
