### ISSUE TITLE
crashes while generating secret manifest

### ISSUE THREAD

**Issue by shaunc** [kubernetes/kubectl#1159]
**What happened**:

kubectl crashed when trying to generate secret manifest:
```shell
% kubectl create secret generic bastion-k8-secret --from-file=foo=bar -o local/k8-secret.yaml --show-managed-fields=true --dry-run=client
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x536543b]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create.(*CreateSecretOptions).Run(0xc00092a800)
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create/create_secret.go:258 +0x2db
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create.NewCmdCreateSecretGeneric.func1(0xc000930780, {0xc0005289c0, 0x1, 0x6})
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create/create_secret.go:143 +0x74
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000930780, {0xc000528960, 0x6, 0x6})
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e2280)
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.Run(0xc0003e2280)
        /private/tmp/kubernetes-cli-20211216-32334-1o8gs1i/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:105 +0x389
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:31 +0x1e
```

**What you expected to happen**:

kubectl not to crash, print secret manifest

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```
NB first tried using kubectl 1.22 before installing 1.23
- Cloud provider or hardware configuration:
EKS 1.21
- OS (e.g: `cat /etc/os-release`):
```
% sw_vers   
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314
```

**Comment by rikatz** [comment]
/triage accepted
I could reproduce it here, let me check and fix :)

**Comment by rikatz** [comment]
The problem is related to the outputter (the -o you are using is invalid, but in case of other commands it's verified, like create service, or create ingress).

Gonna check if something else is problematic, and also add some unit tests to catch this kind of recursion.

**Comment by shaunc** [comment]
Thanks! ... interesting -- ah -- I should be writing `-o yaml > local/k8-secret.yaml`, right?

**Comment by rikatz** [comment]
Yes you should :) buuut anyway, your mistake found one mistake for us, so thanks for reporting this
