### ISSUE TITLE
panic when running kubectl config set-credentials with certificate credentials 

### ISSUE THREAD

**Issue by kindrowboat** [kubernetes/kubectl#1394]
**What happened**:
When running `kubectl config set-credentials kindrobot --client-key=kindrobot.key --client-certificate=kindrobot.crt --embed-certs=true`, I received a panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x40f9fc]

goroutine 1 [running]:
reflect.mapiternext(0xc0001c4330?)
        /usr/lib/go-1.18/src/runtime/map.go:1378 +0x19
k8s.io/kubernetes/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x1a140a8?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc000319b90, 0xc0000db3a0, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_map.go:297 +0x31a
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x15cae60?, 0xc000138801?, 0xc0003bf5d8?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0003fd860, 0x14fc92f?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0003fd9b0, 0x7fff6875d422?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x15cae60?, 0x824601?, 0xc0003bf5d8?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0003fdc20, 0x14c2092?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0003fdc80, 0x1572280?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc000538fa8, 0xc0006409f8, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_slice.go:42 +0x302
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0007867e0, 0x14c7e51?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0007868d0, 0x0?, 0xc0003bf5c0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc0001b08c0?, 0x0?, 0x0?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000496b80, 0xc0006409a0, 0xc000690300?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:219 +0x82
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc0003bf5c0, {0x164fd00, 0xc0006409a0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:98 +0x158
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0001b08c0, {0x164fd00, 0xc0006409a0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/config.go:299 +0xc9
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x14a5cb0?, {0x1a06bb0?, 0xc0006409a0?}, {0x19fdbc0, 0xc00025df50})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00009c190, {0x1a06bb0, 0xc0006409a0}, {0x19fdbc0, 0xc00025df50})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0003e2320, {0x1a06b60?, 0xc0003bf500}, {0x19fdbc0, 0xc00025df50})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0003e2320, {0x1a06b60, 0xc0003bf500}, {0x19fdbc0, 0xc00025df50})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7f5a3b37d158, 0xc0003e2320}, {0x1a06b60, 0xc0003bf500})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:50 +0x64
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:473
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc00025d7a0}, 0xc00025d7d0, 0xc00025d800, 0xc00025d830, {0xc000521f30, ...}, ...}, ...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:426 +0xa8
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x1a15da8, 0xc00009c460}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc00025cbd0}, 0xc00025cc00, 0xc00025cc30, ...}, ...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/config.go:294 +0xcf8
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.createAuthInfoOptions.run({{0x1a15da8, 0xc00009c460}, {0x7fff6875d422, 0x9}, {0x1, {0x7fff6875d441, 0x21}}, {0x0, {0x0, 0x0}}, ...})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:203 +0x31d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.newCmdConfigSetAuthInfo.func1(0xc000687080?, {0x178c86e?, 0x3?, 0x3?})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:161 +0xf8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000687080, {0xc000597a10, 0x3, 0x3})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x663
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000164dc0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x39c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1bb
```

**What you expected to happen**:
My cert and key to be added to my kubeconfig.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps in https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#normal-user

(n.b. I when making the CSR I left "O" attribute blank, and set "CN" as kindrobot.)

**Anything else we need to know?**:
Adding the base64 encoded cert and key to my kubeconfig manually worked. I.e. I was able to switch contexts to that user and make requests.

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

      Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2022-04-02T14:49:13Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
      Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.7+k3s1", GitCommit:"f7c20e237d0ad0eae83c1ce60d490da70dbddc0e", GitTreeState:"clean", BuildDate:"2023-03-10T22:16:07Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

      Running k3s on a single virtual machine

- OS (e.g: `cat /etc/os-release`):

      PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
      NAME="Debian GNU/Linux"
      VERSION_ID="12"
      VERSION="12 (bookworm)"
      VERSION_CODENAME=bookworm
      ID=debian
      HOME_URL="https://www.debian.org/"
      SUPPORT_URL="https://www.debian.org/support"
      BUG_REPORT_URL="https://bugs.debian.org/"

      (n.b. I'm actually running Debian Sid (unstable))

**Comment by ardaguclu** [comment]
Panic is totally not a good thing but your client version seems pretty old (1.20) comparing to your server(1.25) and this difference is not in supported version skew. Could you please try same command using newer kubectl?. If it panicks again, that would be a clear bug.
