### ISSUE TITLE
Validating webhook with reason and code causes nil pointer deref

### ISSUE THREAD

**Issue by myshkin5** [kubernetes/kubectl#768]
When a validating webhook fills in the reason and code in an `AdmissionResponse`, the response sent to `kubectl` causes a panic from a nil pointer dereference. The response was formed in the webhook with the following code:

```go
	return &admissionV1Beta1.AdmissionResponse{
		Allowed: false,
		Result: &metaV1.Status{
			Status:  "Failure",
			Message: msg,
			Reason:  metaV1.StatusReasonInvalid,
			Code:    http.StatusUnprocessableEntity,
		},
	}
```

This was the resulting stacktrace (with `-v 10` debug output):

```
...
I1119 16:59:57.071007   99534 round_trippers.go:423] curl -k -v -XPOST  -H "Content-Type: application/json" -H "Authorization: Basic ..." -H "User-Agent: kubectl/v1.16.2 (darwin/amd64) kubernetes/c97fe50" -H "Accept: application/json" 'https://.../apis/policy.aspenmesh.io/v1alpha1/namespaces/bookinfo/...'
I1119 16:59:57.137067   99534 round_trippers.go:443] POST https://.../apis/policy.aspenmesh.io/v1alpha1/namespaces/bookinfo/... 422 Unprocessable Entity in 66 milliseconds
I1119 16:59:57.137103   99534 round_trippers.go:449] Response Headers:
I1119 16:59:57.137113   99534 round_trippers.go:452]     Content-Type: application/json
I1119 16:59:57.137122   99534 round_trippers.go:452]     Content-Length: 213
I1119 16:59:57.137130   99534 round_trippers.go:452]     Date: Tue, 19 Nov 2019 23:59:57 GMT
I1119 16:59:57.137176   99534 request.go:968] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"....aspenmesh.io\" denied the request: Unrecognized kind ...","reason":"Invalid","code":422}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1f0a3cb]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x2982440, 0xc005d80320, 0x2798268)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:134 +0x17b
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:114
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply.NewCmdApply.func1(0xc0005ca780, 0xc000428fc0, 0x0, 0x4)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:170 +0x128
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005ca780, 0xc000428f80, 0x4, 0x4, 0xc0005ca780, 0xc000428f80)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fd900, 0x2798458, 0xc00003c180, 0x6)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kubernetes-cli-20191016-64633-1hg1utk/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1e7
```

**Comment by myshkin5** [comment]
I think the panic is caused by a `StatusError` without details ([this](https://github.com/kubernetes/kubectl/blob/7c6594395cffe986220bad4b6f7e35a609f6da7e/pkg/cmd/util/helpers.go#L133) line assumes that there is always details). I see in `errors.NewInvalid` and in `errors.NewGenericServerResponse` details are always getting filled in so not sure what the root cause is yet.

**Comment by seans3** [comment]
Please add the version: `kubectl version`

/sig cli
/area kubectl
/kind bug
/priority P1

**Comment by myshkin5** [comment]
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by brianpursley** [comment]
@myshkin5 I noticed in your trace output the user agent shows "kubectl/v1.16.2".

I looked at the code in question as of v1.16.2, and saw this:
https://github.com/kubernetes/kubernetes/blob/v1.16.2/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go#L134
```
        case kerrors.IsInvalid(err):
		details := err.(*kerrors.StatusError).Status().Details
		s := fmt.Sprintf("The %s %q is invalid", details.Kind, details.Name)
```
It is failing on the Sprintf because details is nil

However starting in v1.17.0, there is a nil check for details that *SHOULD* prevent this.
https://github.com/kubernetes/kubernetes/blob/v1.17.0/staging/src/k8s.io/kubectl/pkg/cmd/util/helpers.go#L135
```
        case kerrors.IsInvalid(err):
		details := err.(*kerrors.StatusError).Status().Details
		s := "The request is invalid"
		if details == nil {
			handleErr(s, DefaultErrorExitCode)
			return
		}
```

Can you try again with kubectl 1.17.0+ and see if the problem still occurs?

**Comment by myshkin5** [comment]
@brianpursley It would be a pain to get my webhook to misbehave in this particular way again.

I'll call this one "accepted by inspection". The code looks good to me. Thanks!

(and thanks @Random-Liu)
