### ISSUE TITLE
SIGSEGV for "describe CSINode" on 1.18.0

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes/kubectl#848]
When running the command `kubectl describe CSINode`, I receive the following:

```sh
$ kubectl describe CSINode
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f9efe8]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.describeCSINode.func1(0x2941740, 0xc000739810, 0xc0007c8c60, 0x0)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4035 +0x498
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.tabbedString(0xc0006a9a68, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4616 +0xbc
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.describeCSINode(0xc0002ce000, 0xc000558e70, 0x294b880, 0xc0002ce000, 0xc000558e70, 0x0)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4023 +0x5c
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*CSINodeDescriber).Describe(0xc0005ac510, 0x0, 0x0, 0xc00045fde0, 0x11, 0x1, 0x203000, 0x203000, 0x203000, 0x0)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe/describe.go:4019 +0xef
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.(*DescribeOptions).Run(0xc0009e6c80, 0x0, 0x2782c40)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:188 +0x4c5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.NewCmdDescribe.func1(0xc0009e3900, 0xc0003ed470, 0x1, 0x1)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:110 +0x9f
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0009e3900, 0xc0003ed440, 0x1, 0x1, 0xc0009e3900, 0xc0003ed440)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x29d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0004ae000, 0xc0000cc120, 0xc0000b4180, 0x3)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/kubernetes-cli-20200326-12631-bz25o4/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d
```

Note that `kubectl get CSINode` works fine:

```sh
$ kubectl get CSINode
NAME                                CREATED AT
travis-test-mcd4r                   2020-03-27T19:35:38Z
travis-test-md-0-586b4d556d-nw68j   2020-03-27T19:37:30Z
```

The "describe" verb on `CSINode` worked fine in 1.17.x

```sh
$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by zhouya0** [comment]
@codenrhoden  I submit this PR to fix this. 
https://github.com/kubernetes/kubernetes/pull/89646

**Comment by brianpursley** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/89646
/kind bug
/close
