### ISSUE TITLE
kubectl version command on Docker Desktop for Mac always returns a "Unable to connect to the server: dial tcp...no such host" error

### ISSUE THREAD

**Issue by asad-mahmood1** [kubernetes/kubectl#874]
I have just started using Kubernetes on my Docker Desktop for Mac and after enabling Kubernetes from the Preferences window, I tried running kubectl version to get the client version and server version. This is what I saw instead:

**$kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on 174.141.176.114:53: no such host**

I then decided to take a look at the kubectl config file by running kubectl config view:

**$kubectl config view**
apiVersion: v1
clusters:
  - cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
current-context: docker-for-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

Prior to this, I had already changed my current context to docker-for-desktop (as you can see in the above config file) but after running kubectl version, I kept seeing the same "Unable to connect to server error". That is very interesting because the above config file shows another address for the server....

After perusing some online threads, I decided to look at the cluster by running kubectl cluster-info.  But this also gave me the same error:

**$kubectl cluster-info
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on 174.141.176.114:53: no such host**

I ran kubectl cluster-info dump and saw the same error yet again:

**$kubectl cluster-info dump
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal on 174.141.176.114:53: no such host**

I have already restarted Docker Desktop and reset the Kubernetes cluster but the error unfortunately doesn't go away. 

Please advise and let me know the best way to solve this issue so that I can use kubectl to run Kubernetes commands locally with Docker Desktop on my Mac laptop. 

Here is also a screenshot showing the version of Docker Desktop for Mac that I am currently running:

<img width="760" alt="Screen Shot 2020-05-28 at 2 25 04 AM" src="https://user-images.githubusercontent.com/30564031/83106469-82496300-a08a-11ea-8192-5dc1a1a5c2ea.png">

**Comment by asad-mahmood1** [comment]
Just figured it out. By default, the server address for the cluster in the kube config file is set to https://kubernetes.docker.internal:<port number>. For Docker Desktop for Mac version 2.3.0.3 and K8s version 1.16.5, this server address needs to be changed to https://localhost:<port number>, where the port number is usually something like 6443. Once I made this change to the server address, I was finally able to connect to the local kube server and use the kubectl command without any issues.

You can change the kube config file by finding the .kube folder in the Users folder on your Mac (it's a hidden folder) and opening the config file in an editor. Then change the server address in the config file and save it.

**Comment by brianpursley** [comment]
Glad you got it figured out.
If the server address is wrong, you might want to open an issue with Docker Desktop for Mac.  They would be the ones who set that address.

**Comment by pnbrown** [comment]
This resolved my issue. Thank you.

**Comment by gcharters** [comment]
Just in case anyone encounters the same issue I had...  Editing the kube config file from `kubernetes.docker.internal` to `localhost` worked, but was getting overwritten each time I restarted kube.  In the end I found that there was something wrong with my /etc/hosts file - it had an entry for `kubernetes.docker.internal`, but I couldn't ping it.  I recreated the /etc/hosts file from scratch and I could then ping `kubernetes.docker.internal`.  Kubectl then started working.

**Comment by SecLoop** [comment]
mac version

```
macos big sur 11.6
```

docker version
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
kubectl version
```
kubectl version --v=7
I0918 17:44:37.046766   58438 loader.go:372] Config loaded from file:  /Users/xxxxx/.kube/config
I0918 17:44:37.047343   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:37.047353   58438 round_trippers.go:438] Request Headers:
I0918 17:44:37.047358   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:37.047362   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:37.048995   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:37.049067   58438 request.go:959] Got a Retry-After 1s response for attempt 1 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:38.052010   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:38.052029   58438 round_trippers.go:438] Request Headers:
I0918 17:44:38.052035   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:38.052040   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:38.053258   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:38.053307   58438 request.go:959] Got a Retry-After 1s response for attempt 2 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:39.057269   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:39.057295   58438 round_trippers.go:438] Request Headers:
I0918 17:44:39.057305   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:39.057312   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:39.059058   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:39.059109   58438 request.go:959] Got a Retry-After 1s response for attempt 3 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:40.059337   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:40.059367   58438 round_trippers.go:438] Request Headers:
I0918 17:44:40.059375   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:40.059382   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:40.060902   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:40.060952   58438 request.go:959] Got a Retry-After 1s response for attempt 4 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:41.064600   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:41.064617   58438 round_trippers.go:438] Request Headers:
I0918 17:44:41.064622   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:41.064627   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:41.065893   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:41.065945   58438 request.go:959] Got a Retry-After 1s response for attempt 5 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:42.069898   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:42.069945   58438 round_trippers.go:438] Request Headers:
I0918 17:44:42.069960   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:42.069972   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:42.072609   58438 round_trippers.go:457] Response Status:  in 2 milliseconds
I0918 17:44:42.072678   58438 request.go:959] Got a Retry-After 1s response for attempt 6 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:43.073128   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:43.073153   58438 round_trippers.go:438] Request Headers:
I0918 17:44:43.073161   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:43.073167   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:43.074932   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:43.074986   58438 request.go:959] Got a Retry-After 1s response for attempt 7 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:44.076268   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:44.076286   58438 round_trippers.go:438] Request Headers:
I0918 17:44:44.076292   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:44.076296   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:44.077693   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:44.077737   58438 request.go:959] Got a Retry-After 1s response for attempt 8 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:45.082764   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:45.082784   58438 round_trippers.go:438] Request Headers:
I0918 17:44:45.082791   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:45.082796   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:45.084247   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
I0918 17:44:45.084295   58438 request.go:959] Got a Retry-After 1s response for attempt 9 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:46.088829   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:46.088873   58438 round_trippers.go:438] Request Headers:
I0918 17:44:46.088887   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:46.088899   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:46.091262   58438 round_trippers.go:457] Response Status:  in 2 milliseconds
I0918 17:44:46.091325   58438 request.go:959] Got a Retry-After 1s response for attempt 10 to https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:47.093526   58438 round_trippers.go:432] GET https://kubernetes.docker.internal:6443/version?timeout=32s
I0918 17:44:47.093547   58438 round_trippers.go:438] Request Headers:
I0918 17:44:47.093555   58438 round_trippers.go:442]     Accept: application/json, */*
I0918 17:44:47.093561   58438 round_trippers.go:442]     User-Agent: kubectl/v1.21.4 (darwin/amd64) kubernetes/3cce4a8
I0918 17:44:47.095153   58438 round_trippers.go:457] Response Status:  in 1 milliseconds
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
I0918 17:44:47.095468   58438 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "an error on the server (\"\") has prevented the request from succeeding",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse"
      }
    ],
    "retryAfterSeconds": 1
  },
  "code": 500
}]
F0918 17:44:47.095510   58438 helpers.go:115] Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00018e001, 0xc000c4a1e0, 0x97, 0xe8)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3c5a180, 0xc000000003, 0x0, 0x0, 0xc000788000, 0x31f5601, 0xa, 0x73, 0x100e100)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:970 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x3c5a180, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc0005948c0, 0x1, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1495
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc000c54000, 0x68, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x288
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x2c7bc00, 0xc000c48000, 0x2b07b00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x935
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/version.NewCmdVersion.func1(0xc000bca000, 0xc000495fd0, 0x0, 0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/version/version.go:79 +0x117
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000bca000, 0xc000495fc0, 0x1, 0x1, 0xc000bca000, 0xc000495fc0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00046edc0, 0xc000190120, 0xc000180030, 0x3)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x3c5a180)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 11 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x2b07a20, 0x2c7bf00, 0xc0003a8000, 0x1, 0xc00019eae0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2b07a20, 0x12a05f200, 0x0, 0x1, 0xc00019eae0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x2b07a20, 0x12a05f200, 0xc00019eae0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96
```

**Comment by kuritka** [comment]
Hi,
I had the same issue on my mac except instead of `kubernetes.docker.internal` kubectl wanted to connect to `host.docker.internal`.

The problem was missing record in `/etc/hosts` so I altered following line at the end of the file:
```shell
127.0.0.1 host.docker.internal
# in your case you would add
# 127.0.0.1 kubernetes.docker.internal
```

constantly rewriting kube config (ususally `~/.kube/config`) as mentioned above is a bad solution.
