### ISSUE TITLE
kubectl get po returns an error

### ISSUE THREAD

**Issue by lukaszgryglicki** [kubernetes/kubectl#974]
**What happened**: running `kubectl get po` returned error.

**What you expected to happen**: a list of running pods.

**How to reproduce it (as minimally and precisely as possible)**:
This probably happens under heavy load.

**Anything else we need to know?**:
This is the error:
```
k get po
runtime: failed to create new OS thread (have 7 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x1abcebd, 0x9)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.newosproc(0xc00045a380)
	/usr/local/go/src/runtime/os_linux.go:166 +0x1bd
runtime.newm1(0xc00045a380)
	/usr/local/go/src/runtime/proc.go:1861 +0xdf
runtime.newm(0x0, 0xc000050a00)
	/usr/local/go/src/runtime/proc.go:1840 +0x8f
runtime.startm(0xc000050a00, 0x3092200)
	/usr/local/go/src/runtime/proc.go:1977 +0x12c
runtime.handoffp(0xc000050a00)
	/usr/local/go/src/runtime/proc.go:2004 +0x52
runtime.entersyscallblock_handoff()
	/usr/local/go/src/runtime/proc.go:2928 +0x30
runtime.systemstack(0x458d09)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153

goroutine 1 [syscall, locked to thread]:
runtime.notetsleepg(0x3091ad8, 0xffffffffffffffff, 0xc000060f00)
	/usr/local/go/src/runtime/lock_futex.go:227 +0x34 fp=0xc0003599b0 sp=0xc000359980 pc=0x40a984
runtime.gcBgMarkStartWorkers()
	/usr/local/go/src/runtime/mgc.go:1785 +0x90 fp=0xc0003599f0 sp=0xc0003599b0 pc=0x41ba90
runtime.gcStart(0x1, 0x0, 0x0)
	/usr/local/go/src/runtime/mgc.go:1264 +0x1a1 fp=0xc000359a60 sp=0xc0003599f0 pc=0x41a721
runtime.mallocgc(0x280, 0x183ad60, 0x307de01, 0xc000237680)
	/usr/local/go/src/runtime/malloc.go:1032 +0x3f0 fp=0xc000359b00 sp=0xc000359a60 pc=0x40bbe0
runtime.makeslice(0x183ad60, 0x0, 0x26, 0xc000237708)
	/usr/local/go/src/runtime/slice.go:49 +0x6c fp=0xc000359b30 sp=0xc000359b00 pc=0x443e9c
k8s.io/kubernetes/vendor/github.com/go-openapi/swag.(*NameProvider).GetJSONNames(0xc0002b4270, 0x1a89d60, 0xc00044f440, 0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/swag/json.go:265 +0x1cc fp=0xc000359c58 sp=0xc000359b30 pc=0x112a8ac
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00044f440, 0xc0002f72e9, 0x3d, 0x8b17, 0x7fc378be5108, 0xc00044f440)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:574 +0x25c fp=0xc000359f60 sp=0xc000359c58 pc=0x1158d4c
encoding/json.(*decodeState).object(0xc00043de00, 0x19c5e00, 0xc00044f440, 0x199, 0xc00043de28, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:611 +0x2336 fp=0xc00035a220 sp=0xc000359f60 pc=0x75f6d6
encoding/json.(*decodeState).value(0xc00043de00, 0x19c5e00, 0xc00044f440, 0x199, 0xc000454240, 0x99)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035a288 sp=0xc00035a220 pc=0x75bc8e
encoding/json.(*decodeState).object(0xc00043de00, 0x188d3e0, 0xc00044f3a0, 0x195, 0xc00043de28, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:763 +0x18bc fp=0xc00035a548 sp=0xc00035a288 pc=0x75ec5c
encoding/json.(*decodeState).value(0xc00043de00, 0x188d3e0, 0xc00044f3a0, 0x195, 0x188d3e0, 0xc00044f3a0)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035a5b0 sp=0xc00035a548 pc=0x75bc8e
encoding/json.(*decodeState).object(0xc00043de00, 0x17eaee0, 0xc00044f200, 0x16, 0xc00043de28, 0xc00045007b)
	/usr/local/go/src/encoding/json/decode.go:763 +0x18bc fp=0xc00035a870 sp=0xc00035a5b0 pc=0x75ec5c
encoding/json.(*decodeState).value(0xc00043de00, 0x17eaee0, 0xc00044f200, 0x16, 0xc00035a920, 0x76d164)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035a8d8 sp=0xc00035a870 pc=0x75bc8e
encoding/json.(*decodeState).unmarshal(0xc00043de00, 0x17eaee0, 0xc00044f200, 0xc00043de28, 0x0)
	/usr/local/go/src/encoding/json/decode.go:179 +0x209 fp=0xc00035a960 sp=0xc00035a8d8 pc=0x75b3b9
encoding/json.Unmarshal(0xc0002f7182, 0x67b, 0x8c7e, 0x17eaee0, 0xc00044f200, 0x26, 0x0)
	/usr/local/go/src/encoding/json/decode.go:106 +0x123 fp=0xc00035a9a8 sp=0xc00035a960 pc=0x75ad93
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc00032efc0, 0xc0002f7182, 0x67b, 0x8c7e, 0x7fc378be5108, 0xc00032efc0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x88 fp=0xc00035acb0 sp=0xc00035a9a8 pc=0x1158b78
encoding/json.(*decodeState).object(0xc0002c2460, 0x19c5e00, 0xc00032efc0, 0x199, 0xc0002c2488, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:611 +0x2336 fp=0xc00035af70 sp=0xc00035acb0 pc=0x75f6d6
encoding/json.(*decodeState).value(0xc0002c2460, 0x19c5e00, 0xc00032efc0, 0x199, 0xc00044efc0, 0x99)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035afd8 sp=0xc00035af70 pc=0x75bc8e
encoding/json.(*decodeState).object(0xc0002c2460, 0x18ba360, 0xc0002bef48, 0x195, 0xc0002c2488, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:763 +0x18bc fp=0xc00035b298 sp=0xc00035afd8 pc=0x75ec5c
encoding/json.(*decodeState).value(0xc0002c2460, 0x18ba360, 0xc0002bef48, 0x195, 0x18ba360, 0xc0002bef48)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035b300 sp=0xc00035b298 pc=0x75bc8e
encoding/json.(*decodeState).object(0xc0002c2460, 0x17eaee0, 0xc0002bed80, 0x16, 0xc0002c2488, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:763 +0x18bc fp=0xc00035b5c0 sp=0xc00035b300 pc=0x75ec5c
encoding/json.(*decodeState).value(0xc0002c2460, 0x17eaee0, 0xc0002bed80, 0x16, 0xc0000ef670, 0x76d164)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035b628 sp=0xc00035b5c0 pc=0x75bc8e
encoding/json.(*decodeState).unmarshal(0xc0002c2460, 0x17eaee0, 0xc0002bed80, 0xc0002c2488, 0x0)
	/usr/local/go/src/encoding/json/decode.go:179 +0x209 fp=0xc00035b6b0 sp=0xc00035b628 pc=0x75b3b9
encoding/json.Unmarshal(0xc0002f0000, 0x9d38, 0xfe00, 0x17eaee0, 0xc0002bed80, 0x3092220, 0x7fc37ae4d008)
	/usr/local/go/src/encoding/json/decode.go:106 +0x123 fp=0xc00035b6f8 sp=0xc00035b6b0 pc=0x75ad93
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.(*Schema).UnmarshalJSON(0xc0002beb40, 0xc0002f0000, 0x9d38, 0xfe00, 0x7fc378be5108, 0xc0002beb40)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/schema.go:555 +0x88 fp=0xc00035ba00 sp=0xc00035b6f8 pc=0x1158b78
encoding/json.(*decodeState).object(0xc0002c23c0, 0x1a89d60, 0xc0002beb40, 0x16, 0xc0002c23e8, 0x7b)
	/usr/local/go/src/encoding/json/decode.go:611 +0x2336 fp=0xc00035bcc0 sp=0xc00035ba00 pc=0x75f6d6
encoding/json.(*decodeState).value(0xc0002c23c0, 0x1a89d60, 0xc0002beb40, 0x16, 0xc0000efd70, 0x76d164)
	/usr/local/go/src/encoding/json/decode.go:381 +0x6e fp=0xc00035bd28 sp=0xc00035bcc0 pc=0x75bc8e
encoding/json.(*decodeState).unmarshal(0xc0002c23c0, 0x1a89d60, 0xc0002beb40, 0xc0002c23e8, 0x0)
	/usr/local/go/src/encoding/json/decode.go:179 +0x209 fp=0xc00035bdb0 sp=0xc00035bd28 pc=0x75b3b9
encoding/json.Unmarshal(0xc0002f0000, 0x9d39, 0xfe00, 0x1a89d60, 0xc0002beb40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:106 +0x123 fp=0xc00035bdf8 sp=0xc00035bdb0 pc=0x75ad93
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.Swagger20Schema(0xc0002b9400, 0xc0000efec8, 0x115aad6)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:82 +0xb8 fp=0xc00035be60 sp=0xc00035bdf8 pc=0x11593a8
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/spec.go:66
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.initResolutionCache(0xc000291ad0, 0xc000291aa0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:57 +0x27 fp=0xc00035beb8 sp=0xc00035be60 pc=0x1154447
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init.0()
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/cache.go:51 +0x22 fp=0xc00035bed8 sp=0xc00035beb8 pc=0x11543d2
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init()
	<autogenerated>:1 +0xc5 fp=0xc00035bee8 sp=0xc00035bed8 pc=0x115ac85
k8s.io/kubernetes/vendor/sigs.k8s.io/kustomize/pkg/transformers/config.init()
	<autogenerated>:1 +0x5e fp=0xc00035bef8 sp=0xc00035bee8 pc=0x119363e
k8s.io/kubernetes/vendor/sigs.k8s.io/kustomize/pkg/transformers.init()
	<autogenerated>:1 +0x59 fp=0xc00035bf08 sp=0xc00035bef8 pc=0x119d069
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer/hash.init()
	<autogenerated>:1 +0x63 fp=0xc00035bf18 sp=0xc00035bf08 pc=0x119e4b3
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/kustomize/k8sdeps/transformer.init()
	<autogenerated>:1 +0x45 fp=0xc00035bf28 sp=0xc00035bf18 pc=0x11c5725
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/kustomize/k8sdeps.init()
	<autogenerated>:1 +0x4a fp=0xc00035bf38 sp=0xc00035bf28 pc=0x11c768a
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/kustomize.init()
	<autogenerated>:1 +0x4a fp=0xc00035bf48 sp=0xc00035bf38 pc=0x11d3aaa
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.init()
	<autogenerated>:1 +0xf7 fp=0xc00035bf58 sp=0xc00035bf48 pc=0x11eaa27
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.init()
	<autogenerated>:1 +0x52 fp=0xc00035bf68 sp=0xc00035bf58 pc=0x121d612
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd.init()
	<autogenerated>:1 +0x4a fp=0xc00035bf78 sp=0xc00035bf68 pc=0x132da8a
k8s.io/kubernetes/pkg/kubectl/cmd.init()
	<autogenerated>:1 +0x7f fp=0xc00035bf88 sp=0xc00035bf78 pc=0x16efaef
main.init()
	<autogenerated>:1 +0x68 fp=0xc00035bf98 sp=0xc00035bf88 pc=0x1736fe8
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x1c8 fp=0xc00035bfe0 sp=0xc00035bf98 pc=0x42eda8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00035bfe8 sp=0xc00035bfe0 pc=0x45ad51

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x3091260)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1018 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:404 +0x6c
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: packet.com bare metal servers (4 nodes) Ubuntu 20.04
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by eddiezane** [comment]
Cheers @lukaszgryglicki - 1.16 is a bit out of support. Are you able to reproduce this with a [supported version](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl)?

**Comment by lukaszgryglicki** [comment]
Nope, I don't have anything other. I'll soon update to v1.20 anyway...

**Comment by eddiezane** [comment]
Please reopen if you run into this again after upgrading.

/close
